### ISSUE TITLE
Problems with the height of the drop menu

### ISSUE THREAD

**Issue by JuryM** [CodyHouse/cd-drop-menu-changelog#1]
👋 Thank you for your inspiring work!
There are some issues with drop menu. It turned out that if the second level list is larger than the first list, it does not work correctly.
Tested in macOS Big Sur 11.4 / Safari 14.1.1, Google Chrome 91.0.4472.114
![drop_menu-sc](https://user-images.githubusercontent.com/3930165/124477657-ee79b880-ddac-11eb-8235-c30b3da15303.gif)

**Comment by yankeyhotel** [comment]
I am having the same problem. It's also showing up in the mobile version too. The easiest way to replicate the problem is to delete the last 6 `drop-menu__link` in the demo. Then in a mobile size window you can see that everything is cut off.

It looks like `drop-menu__inner` isn't expanding to the full height.

<img width="1361" alt="Screen Shot 2021-07-22 at 3 52 14 PM" src="https://user-images.githubusercontent.com/1146801/126708198-cf98f944-8828-46f1-935c-d36d6162a660.png">
<img width="1361" alt="Screen Shot 2021-07-22 at 3 52 24 PM" src="https://user-images.githubusercontent.com/1146801/126708195-47cfe47c-382d-41df-a9a2-fef08c8e5fd7.png">
<img width="1361" alt="Screen Shot 2021-07-22 at 3 53 23 PM" src="https://user-images.githubusercontent.com/1146801/126708194-488c0149-3800-46a0-8d45-91127fc6a66d.png">
<img width="1361" alt="Screen Shot 2021-07-22 at 3 53 28 PM" src="https://user-images.githubusercontent.com/1146801/126708190-a89cc9d4-5948-41e0-bfd6-240fff0bf270.png">
<img width="1361" alt="Screen Shot 2021-07-22 at 3 56 25 PM" src="https://user-images.githubusercontent.com/1146801/126708453-feb93230-0223-45b9-81bc-caf867fdfcca.png">

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We just pushed an updated version of the component that fixes the bug. You can get the updated code here:
https://codyhouse.co/ds/components/app/drop-menu

Feel free to reopen the issue if you are still experiencing problems. 

Cheers!
